server:
  port: 8090
  servelt:
    content-path: /dev

swagger2:
  host: 127.0.0.1:8090

#设定访问API doc的路由
springfox:
  documentation:
    swagger:
      v2:
        host: 127.0.0.1:8090
        path: /api-docs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydemo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  # 搜索指定包别名
  type-aliases-package: com.xiyan.mydemo.pojo
